name: "SonarCloud Scan GitHub Actions"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to the latest version supporting Node.js 20
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.5  # Use the correct stable version
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=swaraj1-sys
            -Dsonar.projectKey=SonarCloudCodeAnalysis
            -Dsonar.python.coverage.reportPaths=coverage.xml
