name: "SonarCloud Scan GitHub Actions"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to the latest version supporting Node.js 20
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.11 # Ensure you use the latest version that supports Node.js 20
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=swaraj1-sys
            -Dsonar.projectKey=SonarCloudCodeAnalysis
            -Dsonar.python.coverage.reportPaths=coverage.xml
